from Company.interfaces_response.get_company_response import GetCompanyResponse
from Company.interfaces_response.create_company_response import CreateCompanyResponse
from Company.interfaces_response.get_all_companies_response import GetAllCompanyResponse
from Company.interfaces_response.delete_company_response import DeleteCompanyResponse
from Company.interfaces_response.update_company_response import UpdateCompanyResponse
