"""Update time_created Company model 1

Revision ID: 1dd26cb6a9cb
Revises: 14ea3394c56c
Create Date: 2024-09-19 14:54:12.336441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd26cb6a9cb'
down_revision = '14ea3394c56c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
