"""Update fields

Revision ID: 2b5bdbf2e1cf
Revises: 2e98d3b33395
Create Date: 2024-10-14 22:17:30.580626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5bdbf2e1cf'
down_revision = '2e98d3b33395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
