"""Change company_id

Revision ID: 39e69c421bb7
Revises: 1dd26cb6a9cb
Create Date: 2024-09-24 18:08:10.968072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e69c421bb7'
down_revision = '1dd26cb6a9cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
