"""Update time_created Company model

Revision ID: 14ea3394c56c
Revises: bcf6a4598679
Create Date: 2024-09-19 14:44:36.916050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ea3394c56c'
down_revision = 'bcf6a4598679'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
