"""Update fields Company model

Revision ID: bcf6a4598679
Revises: 4e0a9cb029c3
Create Date: 2024-09-19 12:35:41.835732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcf6a4598679'
down_revision = '4e0a9cb029c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('order_number', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('main_screen_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('company_image', sa.String(), nullable=True))
    op.add_column('company', sa.Column('company_icon', sa.String(), nullable=True))
    op.add_column('company', sa.Column('age_limit', sa.Boolean(), nullable=True))
    op.add_column('company', sa.Column('work_state', sa.Boolean(), nullable=True))
    op.add_column('company', sa.Column('creator_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('company', sa.Column('updater_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('company', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('company', sa.Column('over_time', sa.Time(), nullable=True))
    op.drop_column('company', 'mainScreenID')
    op.drop_column('company', 'updaterId')
    op.drop_column('company', 'creatorId')
    op.drop_column('company', 'startTime')
    op.drop_column('company', 'orderNumber')
    op.drop_column('company', 'workState')
    op.drop_column('company', 'groupID')
    op.drop_column('company', 'companyImage')
    op.drop_column('company', 'overTime')
    op.drop_column('company', 'ageLimit')
    op.drop_column('company', 'companyIcon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('companyIcon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('ageLimit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('overTime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('companyImage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('groupID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('workState', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('orderNumber', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('startTime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('creatorId', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('updaterId', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('mainScreenID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('company', 'over_time')
    op.drop_column('company', 'start_time')
    op.drop_column('company', 'updater_id')
    op.drop_column('company', 'creator_id')
    op.drop_column('company', 'work_state')
    op.drop_column('company', 'age_limit')
    op.drop_column('company', 'company_icon')
    op.drop_column('company', 'company_image')
    op.drop_column('company', 'group_id')
    op.drop_column('company', 'main_screen_id')
    op.drop_column('company', 'order_number')
    # ### end Alembic commands ###
